package org.rsbot.constants;

public enum IBank {
  BANK(762),
  BUTTON_CLOSE(43),
  BUTTON_DEPOSIT_BEAST_INVENTORY(38),
  BUTTON_DEPOSIT_CARRIED_ITEMS(34),
  BUTTON_DEPOSIT_WORN_ITEMS(36),
  BUTTON_HELP(44),
  BUTTON_INSERT(15),
  BUTTON_ITEM(19),
  BUTTON_NOTE(19),
  BUTTON_SEARCH(17),
  BUTTON_SWAP(15),
  BUTTON_OPEN_EQUIP(117),
  INVENTORY(93),
  ITEM_FREE_COUNT(29),
  ITEM_FREE_MAX(30),
  ITEM_MEMBERS_COUNT(31),
  ITEM_MEMBERS_MAX(32),
  SCROLLBAR(114),
  SEARCH(752),
  SEARCH_INPUT(5),
  EQUIPMENT(667),
  EQUIPMENT_COMPONENT(7),
  COLLECTION_BOX(105),
  COLLECTION_BOX_CLOSE(13),
  TAB( 63, 61, 59, 57, 55, 53, 51, 49, 47 ),
  TAB_FIRST_ITEM( 78, 79, 80, 81, 82, 83, 84, 85, 86 ),
  DEPOSIT_BOX(11),
  DEPOSIT_BOX_BUTTON_CLOSE(15),
  DEPOSIT_BUTTON_DEPOSIT_BEAST_INVENTORY(22),
  DEPOSIT_BUTTON_DEPOSIT_CARRIED_ITEMS(18),
  DEPOSIT_BUTTON_DEPOSIT_WORN_ITEMS(20);
  
  final int[] ID;
  
  IBank(final int... id) {
    this.ID = id;
  }
  
  public final int getID() {
    return this.ID[0];
  }
  
  public final int[] getIDs() {
    return this.ID;
  }
}
